### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by grey-cat-1908** [MelisaDev/melisa#3]
- [ ] Models
  - [ ] Connected with Guild
  - [ ] Connected with Channel
  - [ ] Connected with Guild Member
  - [ ] Connected with Guild Role
  - [ ] Connected with Emoji
  - [ ] Connected with Sticker
  - [ ] Connected with Voice
  - [ ] Connected with Webhook
  - [ ] Connected with Invite
  - [ ] Connected with Guild Template
  - [ ] Connected with Guild Sheduled Event
  - [ ] Connected with Audit Log
  - [ ] Connected with Stage Instance
  - [ ] All that connected with Interactions
- [ ] Core
  - [ ] Add some new methods to HTTPClient
  - [ ] Add property to set mobile status
  - [ ] Add Rate Limits handler
  - [ ] Add Threads support
  - [ ] Add support to every gateway event
- [ ] Sharding
- [ ] Cache Configuration
- [ ] Cache Events
- [ ] Cache Container
- [ ] Clusterization
- [ ] Interactions 
- [ ] Voice connection
- [ ] Permissions converter

**Comment by arslee07** [comment]
maybe it's better to use [projects](https://github.com/MelisaDev/melisa/projects) or [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)?

**Comment by grey-cat-1908** [comment]
> maybe it's better to use [projects](https://github.com/MelisaDev/melisa/projects) or [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)?

yeah, you are right i think
